### PR TITLE
Add SilverCableTile

### PR DESCRIPTION
**Pull request by RandomAltThing**
The SilverCable and CopperCable are basically the same, but one of them will cost more to make and may (in the future) be able to output more power for certain machines. Copper and silver cables cannot join together.

### CODE REVIEW

**Comment by CrazyWolf23** [comment]
We will add in what we want added when we want to add them, this addon is still in process.

**Comment by RandomAltThing** [comment]
@jv110 Can you look at it? CrazyWolf can't just close things because they got write access. That's like me closing their pull requests before they had write access. I'm also working on a computer that can control these industrial machines - I have the block I'm just trying to do the texture them.im gonna try and to some GUI.

**Comment by CrazyWolf23** [comment]
@RandomAltThing Im not just closing them for fun, i closed the last three because us two decided we didnt want them in our mod.

**Comment by RandomAltThing** [comment]
@CrazyWolf23 I understand why you closed the other 2 - 1 of them I kept typing the file wrong ans the other was useful but not needed at this.point in time. But this can be useful once we implement power for the cables.

**Comment by RandomAltThing** [comment]
If you think this isknt useful then remove CopperCableTile

**Comment by RandomAltThing** [comment]
Excuse my spelling ^^

**Comment by CrazyWolf23** [comment]
@RandomAltThing I never said that the silver cable wasnt useful, i said we will add in what we want when we want to.

**Comment by RandomAltThing** [comment]
What's the point of making it open source if you get moaned at for making Pull Requests?

**Comment by RandomAltThing** [comment]
You made pull requests for fixing the names bug... nobody complained to you about that.

**Comment by CrazyWolf23** [comment]
I never made a pull request for names bug, link to request please.

**Comment by RandomAltThing** [comment]
@Crazywolf23. https://github.com/jv110/PocketIndustrialization/pull/3

**Comment by CrazyWolf23** [comment]
He Didnt complain because he asked me to fix that bug.

**Comment by RandomAltThing** [comment]
What's your twitter? @crazywolf23

**Comment by CrazyWolf23** [comment]
@CrazyWolf23_YT_

**Comment by CrazyWolf23** [comment]
What yours @RandomAltThing

**Comment by RandomAltThing** [comment]
@CrazyWolf23 I think its @TheDiamondYT

**Comment by RandomAltThing** [comment]
And yes, that github is mine too but its emtpy

**Comment by RandomAltThing** [comment]
I also have the texture and item for SilverCable done.

**Comment by CrazyWolf23** [comment]
Can you push the item and texture to your version please

**Comment by RandomAltThing** [comment]
To my fork? And I can't push the texture because it won't let me but I can upload it and you can if you like

**Comment by RandomAltThing** [comment]
@Crazywolf23 I'm committing to my fork but you will have to push the texture

**Comment by CrazyWolf23** [comment]
Send me texture through Twitter @RandomAltThing

**Comment by RandomAltThing** [comment]
I did @Crazywolf23

**Comment by RandomAltThing** [comment]
@Crazywolf23 Can you implement PlaceableItem AFTER (if it does) this pull request gets merged? If its before then github won't let you merge it.

**Pull request closed without merging**
