### PR TITLE
Updated some things

### PR DESCRIPTION
**Pull request by RandomAltThing**
Sorry about the amount of commits for README.md, I kept forgetting how to make the check box :P

### CODE REVIEW

**Comment by jv110** [comment]
Why the "Addon" in the name?

**Comment by RandomAltThing** [comment]
The mod name stays the same, just when you are on the Installing app screen it will show addon

**Comment by RandomAltThing** [comment]
Please lock this is you can

**Comment by jv110** [comment]
I will still implement this; but by an commit, and fixing your mistakes.

**Comment by RandomAltThing** [comment]
What mistakes? With README?

**Comment by RandomAltThing** [comment]
There is no mistakes anywhere else; I tested this code before.

**Pull request closed without merging**
